# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build Ingestion service image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Ingestion service image
      inputs:
        containerRegistry: 'VIAcode DockerHub'
        repository: 'viacode/ai-core-file-ingestion'
        command: 'buildAndPush'
        dockerfile: 'Ingestion/FileIngestion/Service/Dockerfile'
        tags: |
          $(tag)
