apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-aicore-file-ingestion-ip"
spec:
  selector:
    app: "{{ .Values.global.environment.name }}-aicore-file-ingestion"
  type: ClusterIP
  ports:
    - port: {{ .Values.global.ingestion.service.port }}
      targetPort: {{ .Values.service.containerPort }}