apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.environment.namespace }}
  name: "{{ .Values.global.environment.name }}-aicore-file-ingestion-ingress"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.global.environment.namespace }}-{{ .Values.global.environment.name }}-aicore-file-ingestion-strip-prefix-middleware@kubernetescrd
{{- if not (default false .Values.global.tls.createSecret) }}
    cert-manager.io/cluster-issuer: "{{ .Values.global.environment.name }}-letsencrypt-issuer"
    acme.cert-manager.io/http01-edit-in-place: "true"
{{- end }}
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.global.app.domain }}
    secretName: "{{ .Values.global.environment.name }}-ingress-tls"
  rules:
  - host: "{{ .Values.global.app.domain }}"
    http:
      paths:
      - path: /{{ .Values.global.ingestion.service.urlPrefix }}
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.global.environment.name }}-aicore-file-ingestion-ip"
            port:
              number: {{ .Values.global.ingestion.service.port }}