apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-aicore-qdrant-loadbalancer"
spec:
  selector:
    app: "{{ .Values.global.environment.name }}-aicore-qdrant"
  type: {{ .Values.loadBalancerType }}
  ports:
    - port: {{ .Values.global.ingestion.qdrant.port }}
      targetPort: {{ .Values.qdrant.containerPort }}