apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: {{ .Values.global.environment.namespace }}
  name: "{{ .Values.global.environment.name }}-aicore-api-ingressroute"
spec:
  entryPoints:
  - websecure
  tls:
    secretName: "{{ .Values.global.environment.name }}-ingress-tls"
    domains:
    - main: {{ .Values.global.app.domain }}
      sans:
      - {{ .Values.global.app.domain }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.app.domain }}`) && PathPrefix(`/api`)
    services:
    - name: "{{ .Values.global.environment.name }}-aicore-api-ip"
      port: {{ .Values.global.aicore.service.port }}