apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-aicore-postgres-secret"
type: Opaque
data:
  userName: {{ .Values.postgres.userName | b64enc | quote }}
  {{ if .Values.postgres.password }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 32 }}
  {{ end }}