apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.environment.namespace }}
  name: "{{ .Values.global.environment.name }}-aicore-api"
  labels:
    app: "{{ .Values.global.app.name }}"
    env: "{{ .Values.global.environment.namespace }}"
    build: "{{ .Values.global.app.build }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.global.environment.name }}-aicore-api"
  template:
    metadata:
      labels:
        app: "{{ .Values.global.environment.name }}-aicore-api"
        env: "{{ .Values.global.environment.namespace }}"
        build: "{{ .Values.global.app.build }}"
      {{- if eq .Values.global.app.enableMonitoring "True" }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.aicore.containerPort }}"
      {{- end }}
    spec:
      containers:
        - name: "{{ .Values.global.environment.name }}-aicore-api"
          image: "{{ .Values.global.containerRegistry.name }}/ai-core:{{ .Values.global.aicore.service.tag }}"
          ports:
            - containerPort: {{ .Values.aicore.containerPort }}
          env:
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.environment.name }}-aicore-postgres-secret"
                  key: userName
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.environment.name }}-aicore-postgres-secret"
                  key: password
          envFrom:
            - configMapRef:
                name: "{{ .Values.global.environment.name }}-aicore-api-config"
            - configMapRef:
                name: "{{ .Values.global.environment.name }}-aicore-api-feature-config"
          imagePullPolicy: "{{ .Values.global.containerRegistry.imagePullPolicy }}"
      {{- if .Values.global.containerRegistry.dockerConfig }}
      imagePullSecrets:
        - name: "{{ .Values.global.environment.name }}-acr-secret"
      {{- end }}