apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-aicore-redis-ip"
spec:
  selector:
    app: "{{ .Values.global.environment.name }}-aicore-redis"
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}