{{- if not (default false .Values.global.tls.createSecret) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: {{ .Values.global.environment.namespace }}
  name: "{{ .Values.global.environment.name }}-letsencrypt-issuer"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: AICatalystTeam@VIAcode.com
    privateKeySecretRef:
      name: "{{ .Values.global.environment.name }}-letsencrypt-issuer"
    solvers:
    - http01:
        ingress:
          class: traefik
{{- end }}