{{- if .Values.global.containerRegistry.dockerConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.global.environment.name }}-acr-secret"
  namespace: "{{ .Values.global.environment.namespace }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .Values.global.containerRegistry.dockerConfig }}"
{{- end }}
