loadbalancertype: ClusterIP

postgres:
  storageSize: 16Gi
  internal: "True"
  host: ""
  port: "5432"
  dbName: "aicoredb"
  userName: "aicoredbuser@viacode.com"
  password: "default"

redis:
  port: "6379"
  userName: "aicatalyst@viacode.com"
  password: "AiCatalystIsTheBest!"

featureFlags:
  demoMode: false
  tagging: true
  settings: true
  spentManagement: true
  speechToText: true

aicore:
  containerPort: 8080
  proxy:
  useSearchTab: "false"
  useInternalUsers: "true"

  openAi:
    plannerPrompt: "{{pluginsInstructions}}. Take into account current question: {{currentQuestion}}"
  chat:
    minRelevance: "0.25"
    maxHistoryLength: "10"
    noInformationFoundText: "No relevant information found"
  ingestion:
    delay: "10"
    maxFileSize: "209715200"
  auth:
    issuer: "ViacodeAiCore"
    audience: "ViacodeAiClient"
    tokenExpirationMinutes: "60"
    securityKey: ""
    appRegistration:
      clientId: ""
  defaultTheme:
    logoUrl: "/static/images/logo.png"
    mainColor: "#1976d2"
    mainTextColor: "#000000"
    contrastTextColor: "#ffffff"
    menuBackColor1: "#ffffff"
    menuBackColor2: "#f7f7f7"
    backgroundColor: "#ffffff"
    pageTitle: "VIAcode AI Core"