name: Require Any Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, edited]

jobs:
  check-any-label:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if no label is present
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            if (!labels || labels.length === 0) {
              core.setFailed("At least one label is required on this pull request.");
            }
